name:                ky
version:             0.1.0.0
github:              "bagnalla/ky"
license:             BSD3
author:              "Alexander Bagnall"
maintainer:          "ab667712@ohio.edu"
copyright:           "2019 Alexander Bagnall"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bagnalla/ky#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl
  - megaparsec
  - parser-combinators
  - containers
  - random
  - monad-loops
  - sparse-linear-algebra

executables:
  ky-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ky
    - mtl
    - random
    - megaparsec

tests:
  ky-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ky
